catalog:
  "@atlaskit/pragmatic-drag-and-drop": ^1.6.1
  "@atlaskit/pragmatic-drag-and-drop-auto-scroll": ^2.1.0
  "@atlaskit/pragmatic-drag-and-drop-hitbox": ^1.0.3
  "@atlaskit/pragmatic-drag-and-drop-live-region": ^1.3.0
  "@base-ui-components/react": 1.0.0-alpha.8
  "@changesets/cli": ^2.29.4
  "@cloudflare/workers-types": ^4.20250510.0
  "@electric-sql/client": ^1.0.4
  "@electric-sql/pglite": ^0.3.1
  "@electric-sql/react": ^1.0.4
  "@flags-sdk/edge-config": ^0.1.0
  "@hcaptcha/react-hcaptcha": ^1.12.0
  "@million/lint": ^1.0.14
  "@mux/mux-player-react": ^3.4.0
  "@next/bundle-analyzer": ^15.3.2
  "@radix-ui/react-navigation-menu": ^1.2.12
  "@react-spring/shared": ^10.0.0
  "@react-spring/web": ^10.0.0
  "@types/node": ^22.15.17
  "@types/react": ^19.1.4
  "@types/react-dom": ^19.1.4
  "@unkey/api": ^0.36.0
  "@unkey/cache": ^1.5.0
  "@unkey/hono": ^1.4.16
  "@unkey/ratelimit": ^2.0.0
  "@vercel/analytics": ^1.5.0
  "@vercel/speed-insights": ^1.2.0
  "@vercel/toolbar": ^0.1.36
  "@xyflow/react": ^12.6.1
  basehub: ^8.2.7
  client-only: ^0.0.1
  drizzle-kit: ^0.31.1
  drizzle-orm: ^0.43.1
  effect: ^3.15.0
  fast-check: ^4.1.1
  flags: ^4.0.0
  geist: ^1.4.2
  hono: ^4.7.9
  million: ^3.1.11
  motion: ^12.11.0
  next: ^15.3.2
  normalize-wheel: ^1.0.1
  nuqs: ^2.4.3
  react: ^19.1.0
  react-dom: ^19.1.0
  react-markdown: ^10.1.0
  react-split-grid: ^1.0.4
  react-use: ^17.6.0
  resend: ^4.5.1
  semantic-release: ^24.2.3
  server-only: ^0.0.1
  sonner: ^2.0.3
  storybook: ^8.6.12
  tsup: ^8.4.0
  typescript: ^5.8.3
  unstorage: ^1.16.0
  vaul: ^1.1.2
  wrangler: ^4.14.4
  zod: ^3.24.4
  zod-validation-error: ^3.4.1

packages:
  - "@kngsthvs/*"
  - "apps/*"
  - "clis/*"
  - "internal/*"
  - "packages/*"
  - "services/*"
