import type { Metadata } from "next";

export const metadata: Metadata = {
	description: "Generated by hono",
	title: "Hono | nextjs",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
